language: node_js
node_js:
  "8"
jobs:
  include:
    - stage: release
      if: branch = master
      node_js: "8"
      script:
        - npm install --global semantic-release@15
        - semantic-release
